# Generated by Django 3.2 on 2021-04-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(help_text='Фамилия', max_length=30)),
                ('Name', models.CharField(help_text='Имя', max_length=30)),
                ('Patronymic', models.CharField(help_text='Отчество', max_length=30)),
                ('Date_of_birth', models.DateField(blank=True, help_text='Дата рождения', null=True)),
                ('Place_of_birth', models.CharField(help_text='Место рождения', max_length=100)),
                ('Citizenship', models.CharField(help_text='Гражданство', max_length=100)),
                ('Identity_document', models.CharField(help_text='Документ, удостоверяющий личност', max_length=10, verbose_name='Серия номер паспорта')),
                ('When_issued', models.DateField(blank=True, help_text='Когда выдан', null=True)),
                ('Issued_by', models.CharField(help_text='Кем выдан', max_length=100)),
                ('residing_at_the_address', models.CharField(help_text='Проживающий(ей) по адресу', max_length=100)),
                ('personal_phone', models.CharField(help_text='Личный телефон', max_length=11, verbose_name='Номер телефона начиная с +7')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
