# Generated by Django 3.2 on 2021-04-17 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructZapros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model1', models.CharField(help_text='Директору ОГБПОУ «Томский техникум информационных технологий» ', max_length=100)),
                ('Model2', models.CharField(help_text='проживающий(ей) по адресу', max_length=100)),
                ('Model3', models.CharField(help_text='Прошу принять меня в ОГБПОУ «ТТИТ» на обучение по направлению подготовки (профессия / специальность) 1.(приоритетная профессия / специальность)', max_length=100)),
                ('Model4', models.CharField(help_text='(дополнительная профессия / специальность): ', max_length=100)),
                ('Model5', models.CharField(help_text='О себе сообщаю следующее:', max_length=100)),
                ('Model6', models.CharField(help_text='Окончил (а) в 2010 году:', max_length=100)),
                ('Model7', models.CharField(help_text='Уровень образования', max_length=100)),
                ('Model8', models.CharField(help_text='Документ об образовании:', max_length=100)),
                ('Model9', models.CharField(help_text='Английский язык', max_length=100)),
                ('Model10', models.CharField(help_text='Наличие договора о целевом обучении:', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyPlatnik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='№ п/п', primary_key=True, serialize=False)),
                ('Specialty_name', models.CharField(blank=True, choices=[('m', 'Сетевое и системное администрирование'), ('o', 'Информационные системы и программирование (инф. сист.)'), ('a', 'Информационные системы и программирование (web)'), ('r', 'Информационные системы и программирование (о-з)'), ('t', 'Обеспечение информационной безопасности автоматизированных систем')], default='m', help_text='Наименование специалитета', max_length=1)),
                ('Form_of_study', models.CharField(blank=True, choices=[('q', 'очная'), ('w', 'очно-заочная'), ('e', 'заочная')], default='q', help_text='Форма обучения - указать: очно/ очно-заочно/ заочно', max_length=1)),
                ('Training_period', models.CharField(blank=True, choices=[('z', '3 года 10 мес.'), ('x', '2 года 10 мес.')], default='z', help_text='Срок обучения', max_length=1)),
                ('Basic_education', models.CharField(blank=True, choices=[('o', '9 классов'), ('p', '11 классов')], default='o', help_text='Базовое образование', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
