# Generated by Django 3.2 on 2021-04-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210417_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='constructzapros',
            options={'verbose_name': 'Конструктор запросов', 'verbose_name_plural': 'Конструктор запросов'},
        ),
        migrations.AlterModelOptions(
            name='specialtybydhet',
            options={'verbose_name': 'Специальности бюджет', 'verbose_name_plural': 'Специальности бюджет'},
        ),
        migrations.AlterModelOptions(
            name='specialtyplatnik',
            options={'verbose_name': 'Специальности платные', 'verbose_name_plural': 'Специальности платные'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студенты', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
