# Generated by Django 3.2 on 2021-04-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_constructabiturient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructAbiturient',
        ),
    ]
